// Mocks generated by Mockito 5.4.6 from annotations
// in online_exam/test/features/profile/presenstation/view_model/profile_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:online_exam/core/api/result.dart' as _i4;
import 'package:online_exam/features/auth/domain/model/sign_up_response_model.dart'
    as _i9;
import 'package:online_exam/features/profile/domain/entity/user_info_entity.dart'
    as _i5;
import 'package:online_exam/features/profile/domain/usecase/change_password_usecase.dart'
    as _i8;
import 'package:online_exam/features/profile/domain/usecase/edit_user_profile_info_usecase.dart'
    as _i7;
import 'package:online_exam/features/profile/domain/usecase/get_user_profile_info_usecase.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GetProfileInfoUcecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProfileInfoUcecase extends _i1.Mock
    implements _i2.GetProfileInfoUcecase {
  MockGetProfileInfoUcecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.UserInfoEntity>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i3.Future<_i4.Result<_i5.UserInfoEntity>>.value(
              _i6.dummyValue<_i4.Result<_i5.UserInfoEntity>>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.UserInfoEntity>>);
}

/// A class which mocks [EditProfileInfoUcecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockEditProfileInfoUcecase extends _i1.Mock
    implements _i7.EditProfileInfoUcecase {
  MockEditProfileInfoUcecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.UserInfoEntity>> call(_i5.UserEntity? userEntity) =>
      (super.noSuchMethod(
            Invocation.method(#call, [userEntity]),
            returnValue: _i3.Future<_i4.Result<_i5.UserInfoEntity>>.value(
              _i6.dummyValue<_i4.Result<_i5.UserInfoEntity>>(
                this,
                Invocation.method(#call, [userEntity]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.UserInfoEntity>>);
}

/// A class which mocks [ChangePasswordUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockChangePasswordUseCase extends _i1.Mock
    implements _i8.ChangePasswordUseCase {
  MockChangePasswordUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i9.AuthResponseModel>> call(
    String? oldPassword,
    String? password,
    String? rePassword,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [oldPassword, password, rePassword]),
            returnValue: _i3.Future<_i4.Result<_i9.AuthResponseModel>>.value(
              _i6.dummyValue<_i4.Result<_i9.AuthResponseModel>>(
                this,
                Invocation.method(#call, [oldPassword, password, rePassword]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i9.AuthResponseModel>>);
}
