// Mocks generated by Mockito 5.4.6 from annotations
// in online_exam/test/features/profile/data/datasourse/remote_profile_data_sourse_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:mockito/mockito.dart' as _i1;
import 'package:online_exam/core/api/api_client.dart' as _i8;
import 'package:online_exam/features/auth/data/model/forget_password_request_model.dart'
    as _i12;
import 'package:online_exam/features/auth/data/model/login_request_model.dart'
    as _i11;
import 'package:online_exam/features/auth/data/model/reset_password_request.dart'
    as _i14;
import 'package:online_exam/features/auth/data/model/sign_up_request.dart'
    as _i10;
import 'package:online_exam/features/auth/data/model/sign_up_response_dto.dart'
    as _i2;
import 'package:online_exam/features/auth/data/model/verify_reset_code_request_model.dart'
    as _i13;
import 'package:online_exam/features/home/data/model/exam_model_dto.dart'
    as _i5;
import 'package:online_exam/features/home/data/model/subjects_dto.dart' as _i7;
import 'package:online_exam/features/profile/data/model/change_password_request.dart'
    as _i17;
import 'package:online_exam/features/profile/data/model/update_request_dto.dart'
    as _i16;
import 'package:online_exam/features/profile/data/model/user_info_dto.dart'
    as _i6;
import 'package:online_exam/features/questions/data/model/check_questions_request.dart'
    as _i15;
import 'package:online_exam/features/questions/data/model/check_questions_response.dart'
    as _i4;
import 'package:online_exam/features/questions/data/model/questions_response.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSignUpResponseDto_0 extends _i1.SmartFake
    implements _i2.SignUpResponseDto {
  _FakeSignUpResponseDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQuestionsResponse_1 extends _i1.SmartFake
    implements _i3.QuestionsResponse {
  _FakeQuestionsResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCheckQuestionsResponse_2 extends _i1.SmartFake
    implements _i4.CheckQuestionsResponse {
  _FakeCheckQuestionsResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeExamsResponseModelDto_3 extends _i1.SmartFake
    implements _i5.ExamsResponseModelDto {
  _FakeExamsResponseModelDto_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserInfoDto_4 extends _i1.SmartFake implements _i6.UserInfoDto {
  _FakeUserInfoDto_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSubjectsDto_5 extends _i1.SmartFake implements _i7.SubjectsDto {
  _FakeSubjectsDto_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i8.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.SignUpResponseDto> signUp(
    _i10.SignUpRequestModel? signUpRequestModel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [signUpRequestModel]),
            returnValue: _i9.Future<_i2.SignUpResponseDto>.value(
              _FakeSignUpResponseDto_0(
                this,
                Invocation.method(#signUp, [signUpRequestModel]),
              ),
            ),
          )
          as _i9.Future<_i2.SignUpResponseDto>);

  @override
  _i9.Future<_i2.SignUpResponseDto> signIn(
    _i11.LoginRequestModel? loginRequestModel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [loginRequestModel]),
            returnValue: _i9.Future<_i2.SignUpResponseDto>.value(
              _FakeSignUpResponseDto_0(
                this,
                Invocation.method(#signIn, [loginRequestModel]),
              ),
            ),
          )
          as _i9.Future<_i2.SignUpResponseDto>);

  @override
  _i9.Future<_i2.SignUpResponseDto> forgetPassword(
    _i12.ForgetPasswordRequestModel? forgetPasswordRequestModel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [forgetPasswordRequestModel]),
            returnValue: _i9.Future<_i2.SignUpResponseDto>.value(
              _FakeSignUpResponseDto_0(
                this,
                Invocation.method(#forgetPassword, [
                  forgetPasswordRequestModel,
                ]),
              ),
            ),
          )
          as _i9.Future<_i2.SignUpResponseDto>);

  @override
  _i9.Future<_i2.SignUpResponseDto> verifyResetCode(
    _i13.VerifyResetCodeRequestModel? verifyResetCodeRequestModel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetCode, [verifyResetCodeRequestModel]),
            returnValue: _i9.Future<_i2.SignUpResponseDto>.value(
              _FakeSignUpResponseDto_0(
                this,
                Invocation.method(#verifyResetCode, [
                  verifyResetCodeRequestModel,
                ]),
              ),
            ),
          )
          as _i9.Future<_i2.SignUpResponseDto>);

  @override
  _i9.Future<_i2.SignUpResponseDto> resetPassword(
    _i14.ResetPasswordRequest? resetPasswordRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [resetPasswordRequest]),
            returnValue: _i9.Future<_i2.SignUpResponseDto>.value(
              _FakeSignUpResponseDto_0(
                this,
                Invocation.method(#resetPassword, [resetPasswordRequest]),
              ),
            ),
          )
          as _i9.Future<_i2.SignUpResponseDto>);

  @override
  _i9.Future<_i3.QuestionsResponse> getQuestions(String? examId) =>
      (super.noSuchMethod(
            Invocation.method(#getQuestions, [examId]),
            returnValue: _i9.Future<_i3.QuestionsResponse>.value(
              _FakeQuestionsResponse_1(
                this,
                Invocation.method(#getQuestions, [examId]),
              ),
            ),
          )
          as _i9.Future<_i3.QuestionsResponse>);

  @override
  _i9.Future<_i4.CheckQuestionsResponse> checkQuestions(
    _i15.CheckQuestionsRequest? checkQuestionsRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#checkQuestions, [checkQuestionsRequest]),
            returnValue: _i9.Future<_i4.CheckQuestionsResponse>.value(
              _FakeCheckQuestionsResponse_2(
                this,
                Invocation.method(#checkQuestions, [checkQuestionsRequest]),
              ),
            ),
          )
          as _i9.Future<_i4.CheckQuestionsResponse>);

  @override
  _i9.Future<_i5.ExamsResponseModelDto> getAllExamBySubject(String? subject) =>
      (super.noSuchMethod(
            Invocation.method(#getAllExamBySubject, [subject]),
            returnValue: _i9.Future<_i5.ExamsResponseModelDto>.value(
              _FakeExamsResponseModelDto_3(
                this,
                Invocation.method(#getAllExamBySubject, [subject]),
              ),
            ),
          )
          as _i9.Future<_i5.ExamsResponseModelDto>);

  @override
  _i9.Future<_i6.UserInfoDto> getProfileInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getProfileInfo, []),
            returnValue: _i9.Future<_i6.UserInfoDto>.value(
              _FakeUserInfoDto_4(this, Invocation.method(#getProfileInfo, [])),
            ),
          )
          as _i9.Future<_i6.UserInfoDto>);

  @override
  _i9.Future<_i7.SubjectsDto> getAllSubjects() =>
      (super.noSuchMethod(
            Invocation.method(#getAllSubjects, []),
            returnValue: _i9.Future<_i7.SubjectsDto>.value(
              _FakeSubjectsDto_5(this, Invocation.method(#getAllSubjects, [])),
            ),
          )
          as _i9.Future<_i7.SubjectsDto>);

  @override
  _i9.Future<_i6.UserInfoDto> editProfileInfo(
    _i16.UpdateUserModel? userUpdata,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#editProfileInfo, [userUpdata]),
            returnValue: _i9.Future<_i6.UserInfoDto>.value(
              _FakeUserInfoDto_4(
                this,
                Invocation.method(#editProfileInfo, [userUpdata]),
              ),
            ),
          )
          as _i9.Future<_i6.UserInfoDto>);

  @override
  _i9.Future<_i2.SignUpResponseDto> changePassword(
    _i17.ChangePasswordRequest? changePasswordRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [changePasswordRequest]),
            returnValue: _i9.Future<_i2.SignUpResponseDto>.value(
              _FakeSignUpResponseDto_0(
                this,
                Invocation.method(#changePassword, [changePasswordRequest]),
              ),
            ),
          )
          as _i9.Future<_i2.SignUpResponseDto>);
}
