// Mocks generated by Mockito 5.4.6 from annotations
// in online_exam/test/features/home/data/datasourse/remote_data_sourse_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:online_exam/core/api/api_client.dart' as _i4;
import 'package:online_exam/features/auth/data/model/forget_password_request_model.dart'
    as _i8;
import 'package:online_exam/features/auth/data/model/login_request_model.dart'
    as _i7;
import 'package:online_exam/features/auth/data/model/reset_password_request.dart'
    as _i10;
import 'package:online_exam/features/auth/data/model/sign_up_request.dart'
    as _i6;
import 'package:online_exam/features/auth/data/model/sign_up_response_dto.dart'
    as _i2;
import 'package:online_exam/features/auth/data/model/verify_reset_code_request_model.dart'
    as _i9;
import 'package:online_exam/features/home/data/model/exam_model_dto.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSignUpResponseDto_0 extends _i1.SmartFake
    implements _i2.SignUpResponseDto {
  _FakeSignUpResponseDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeExamsResponseModelDto_1 extends _i1.SmartFake
    implements _i3.ExamsResponseModelDto {
  _FakeExamsResponseModelDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i4.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.SignUpResponseDto> signUp(
    _i6.SignUpRequestModel? signUpRequestModel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [signUpRequestModel]),
            returnValue: _i5.Future<_i2.SignUpResponseDto>.value(
              _FakeSignUpResponseDto_0(
                this,
                Invocation.method(#signUp, [signUpRequestModel]),
              ),
            ),
          )
          as _i5.Future<_i2.SignUpResponseDto>);

  @override
  _i5.Future<_i2.SignUpResponseDto> signIn(
    _i7.LoginRequestModel? loginRequestModel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [loginRequestModel]),
            returnValue: _i5.Future<_i2.SignUpResponseDto>.value(
              _FakeSignUpResponseDto_0(
                this,
                Invocation.method(#signIn, [loginRequestModel]),
              ),
            ),
          )
          as _i5.Future<_i2.SignUpResponseDto>);

  @override
  _i5.Future<_i2.SignUpResponseDto> forgetPassword(
    _i8.ForgetPasswordRequestModel? forgetPasswordRequestModel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [forgetPasswordRequestModel]),
            returnValue: _i5.Future<_i2.SignUpResponseDto>.value(
              _FakeSignUpResponseDto_0(
                this,
                Invocation.method(#forgetPassword, [
                  forgetPasswordRequestModel,
                ]),
              ),
            ),
          )
          as _i5.Future<_i2.SignUpResponseDto>);

  @override
  _i5.Future<_i2.SignUpResponseDto> verifyResetCode(
    _i9.VerifyResetCodeRequestModel? verifyResetCodeRequestModel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetCode, [verifyResetCodeRequestModel]),
            returnValue: _i5.Future<_i2.SignUpResponseDto>.value(
              _FakeSignUpResponseDto_0(
                this,
                Invocation.method(#verifyResetCode, [
                  verifyResetCodeRequestModel,
                ]),
              ),
            ),
          )
          as _i5.Future<_i2.SignUpResponseDto>);

  @override
  _i5.Future<_i2.SignUpResponseDto> resetPassword(
    _i10.ResetPasswordRequest? resetPasswordRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [resetPasswordRequest]),
            returnValue: _i5.Future<_i2.SignUpResponseDto>.value(
              _FakeSignUpResponseDto_0(
                this,
                Invocation.method(#resetPassword, [resetPasswordRequest]),
              ),
            ),
          )
          as _i5.Future<_i2.SignUpResponseDto>);

  @override
  _i5.Future<_i3.ExamsResponseModelDto> getAllExamBySubject(String? subject) =>
      (super.noSuchMethod(
            Invocation.method(#getAllExamBySubject, [subject]),
            returnValue: _i5.Future<_i3.ExamsResponseModelDto>.value(
              _FakeExamsResponseModelDto_1(
                this,
                Invocation.method(#getAllExamBySubject, [subject]),
              ),
            ),
          )
          as _i5.Future<_i3.ExamsResponseModelDto>);
}
