// Mocks generated by Mockito 5.4.6 from annotations
// in online_exam/test/features/profile/data/repo/profile_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:online_exam/core/api/result.dart' as _i4;
import 'package:online_exam/features/auth/data/model/sign_up_response_dto.dart'
    as _i8;
import 'package:online_exam/features/profile/data/datasourse/remote_profile_data_sourse.dart'
    as _i2;
import 'package:online_exam/features/profile/data/model/change_password_request.dart'
    as _i9;
import 'package:online_exam/features/profile/data/model/update_request_dto.dart'
    as _i7;
import 'package:online_exam/features/profile/data/model/user_info_dto.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [RemoteProfileDataSourse].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteProfileDataSourse extends _i1.Mock
    implements _i2.RemoteProfileDataSourse {
  MockRemoteProfileDataSourse() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.UserInfoDto>> getUserInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getUserInfo, []),
            returnValue: _i3.Future<_i4.Result<_i5.UserInfoDto>>.value(
              _i6.dummyValue<_i4.Result<_i5.UserInfoDto>>(
                this,
                Invocation.method(#getUserInfo, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.UserInfoDto>>);

  @override
  _i3.Future<_i4.Result<_i5.UserInfoDto>> editUserInfo(
    _i7.UpdateUserModel? entity,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#editUserInfo, [entity]),
            returnValue: _i3.Future<_i4.Result<_i5.UserInfoDto>>.value(
              _i6.dummyValue<_i4.Result<_i5.UserInfoDto>>(
                this,
                Invocation.method(#editUserInfo, [entity]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.UserInfoDto>>);

  @override
  _i3.Future<_i4.Result<_i8.SignUpResponseDto>> changePassword(
    _i9.ChangePasswordRequest? changePasswordRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [changePasswordRequest]),
            returnValue: _i3.Future<_i4.Result<_i8.SignUpResponseDto>>.value(
              _i6.dummyValue<_i4.Result<_i8.SignUpResponseDto>>(
                this,
                Invocation.method(#changePassword, [changePasswordRequest]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i8.SignUpResponseDto>>);
}
